### ISSUE TITLE
pspmigrator throws error for Stateful set and exit when using migrate command

### ISSUE THREAD

**Issue by VarunTyagi86** [kubernetes-sigs/pspmigrator#11]
1) Getting below error due to which i am unable to run  pspmigrator migrate

pspmigrator migrate -d
Checking if any pods are being mutated by a PSP object
2023/05/25 18:27:46 failed to fetch controller: unsupported controller kind StatefulSet

2) For a pod it says Mutating as true but 

teamconnecthelm-rke-chart-78f857f69d-hxdq4                  | teamconnect              | true    | global-unrestricted-psp

But when i run pspmigrator mutating  pod  teamconnecthelm-rke-chart-78f857f69d-hxdq4 -n teamconnect, it doesnot show anything

PSP profile global-unrestricted-psp has the following mutating fields: [] and annotations: []

k get psp global-unrestricted-psp -o yaml
Warning: policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  annotations:
    psp.rke2.io/global-unrestricted: resolved
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
  creationTimestamp: "2022-10-27T01:36:18Z"
  name: global-unrestricted-psp
  resourceVersion: "195"
  uid: 1d4d321c-84c8-48c9-b1e9-ca851e9dc95c
spec:
  allowPrivilegeEscalation: true
  allowedCapabilities:
  - '*'
  fsGroup:
    rule: RunAsAny
  hostIPC: true
  hostNetwork: true
  hostPID: true
  hostPorts:
  - max: 65535
    min: 0
  privileged: true
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - '*'

**Comment by Amith211** [comment]
Also getting `failed to fetch controller: unsupported controller kind StatefulSet`

Any easy workaround, such as skipping that namespace, if StatefulSets are not supported?

**Comment by saidben0** [comment]
Any updates pls? I am facing the same issue.

The output is a bit challenging to read as well :(
```
pspmigrator mutating pod <pod-name>-97b654f74-5btg5 -n <namespace-name>
Pod <pod-name>-97b654f74-5btg5 is mutated by PSP <psp-name>: true, diff: [slice[0]: <nil pointer> != v1.SecurityContext slice[1]: <no value> != nil slice[2]: <no value> != &SecurityContext{Capabilities:&Capabilities{Add:[NET_ADMIN NET_RAW],Drop:[ALL],},Privileged:*false,SELinuxOptions:nil,RunAsUser:*0,RunAsNonRoot:*false,ReadOnlyRootFilesystem:*false,AllowPrivilegeEscalation:*false,RunAsGroup:*0,ProcMount:nil,WindowsOptions:nil,SeccompProfile:nil,} FSGroup: <nil pointer> != int64]
PSP profile <psp-name> has the following mutating fields: [] and annotations: []
```

**Comment by AakarshitAgarwal** [comment]
I am getting the same error, do let us know if there is any fix?

`./pspmigrator migrate
WARNING: the gcp auth plugin is deprecated in v1.22+, unavailable in v1.25+; use gcloud instead.
To learn more, consult https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
Checking if any pods are being mutated by a PSP object
2023/08/18 11:39:15 failed to fetch controller: unsupported controller kind StatefulSet`

I am upgrading my cluster to 1.25 and have to migrate PSP to PSA :(

**Comment by MoxmiNu** [comment]
Also getting errors for Kind Job & StatefulSet when running `pspmigrator mutating pods`
```
$ pspmigrator mutating pods
There are 41 pods in the cluster
2023/10/10 error occured checking if pod is mutated: failed to fetch controller: unsupported controller kind StatefulSet
2023/10/10 error occured checking if pod is mutated: failed to fetch controller: unsupported controller kind Job
```

**Comment by X4mp** [comment]
I am also facing this issue with a RKE2 cluster. The affected resources for me are the same as mentioned above:
* Statefulset
* Job

And the psp listed ist global-unrestricted-psp
