### ISSUE TITLE
pspmigrator mutating pods command returns empty output

### ISSUE THREAD

**Issue by nitinjagjivan** [kubernetes-sigs/pspmigrator#4]
./pspmigrator mutating pods
There are 49 pods in the cluster
+------+-----------+---------+-----+
| NAME | NAMESPACE | MUTATED | PSP |
+------+-----------+---------+-----+
+------+-----------+---------+-----+

**Comment by samos123** [comment]
Sorry I didn't watch the repo initially and must have missed these. Could you elaborate more about your environment? What's the kubeconfig that's being used?

**Comment by milosara78** [comment]
Is this resolved?? Even for me I have the same issue . It returns empty value.
