### ISSUE TITLE
Misleading statement about releases in README.md

### ISSUE THREAD

**Issue by okhotnikov-aa** [kubernetes-sigs/pspmigrator#5]
Hi guys, I see a statement in README.md - that I can download releases from the provided link.
But actually, there is no releases at all

https://github.com/kubernetes-sigs/pspmigrator/blob/9261f26bfec31fc1c40fcc7dc10fee4ae6a5ceb8/README.md?plain=1#L24

**Comment by samos123** [comment]
/remove-lifecycle stale

I think the release was in the old repo and after migrating to kubernetes-sigs this wasn't updated. Thanks for reporting this. Just now noticing the issues. I will fix it by making a release
